[package]
name = "wpdl-epub"
version = "0.1.0-alpha.1"
edition = "2024"
description = "Placeholder"
license = "AGPL-3.0-only"
documentation = "https://docs.rs/placeholder"
homepage = "https://placeholder.dev"

[dependencies]
